---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande
  namespace: default
  annotations:
           prometheus.io/scrape: 'true'
           filter.by.port.name: 'true'
spec:
  selector:
    matchLabels:
      app: commande
  replicas: 1
  template:
    metadata:
      labels:
        app: commande
    spec:
      containers:
      - name: commande
        image: switch2mdock/micro-app:
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: commande
spec:
  type: LoadBalancer
  selector:
    app: commande
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 9002

