---
#if we are running jenkins in docker container we should install the needed tool for deployment
- name: Install java and maeven
  hosts: localhost
  become: yes
  tasks:
    - name: Install wget
      apt:
        name: wget
        state: present
    - name: install java
      command: "{{ item }}"
      with_items:
      - "wget https://download.java.net/java/GA/jdk13.0.1/cec27d702aa74d5a8630c65ae61e4305/9/GPL/openjdk-13.0.1_linux-x64_bin.tar.gz"
      - "tar -xvf openjdk-13.0.1_linux-x64_bin.tar.gz"
      - "mv jdk-13.0.1 /opt/"
      - "JAVA_HOME='/opt/jdk-13.0.1'"
      - "PATH="$JAVA_HOME/bin:$PATH""
      - "export PATH"
    - name: check java version
      command: java version
      register: javaout
    - debug: msg={{javaout}}

    - name: install maeven
      command: "{{ item }}"
      with_items:
      - "wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz"
      - "tar -xvf apache-maven-3.6.3-bin.tar.gz"
      - "mv apache-maven-3.6.3 /opt/"
      - "M2_HOME='/opt/apache-maven-3.6.3'"
      - "PATH="$M2_HOME/bin:$PATH""
      - "export PATH"
    - name: check meaven version
      command: maeven version
      register: mavenout
    - debug: msg={{maveout}}

    - name: Install kubectl
      command: "{{ item }}"
      with_items:
      - "curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl""
      - "curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256""
      - "echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check"
      - "install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"
    - name: check kubectl version
      command: kubectl version --client
      register: kubout
    - debug: msg={{kubout}}

- name: Install terraform
  hosts: localhost
  become: yes
  tasks:
    - name: Install unzip
      apt:
        name: unzip
        state: present
    - name: install terraform
      command: "{{ item }}"
      with_items:
      - "wget https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip"
      - "unzip terraform_1.3.3_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
    - name: check terraform version
      command: terraform version
      register: terout
    - debug: msg={{terout}}